/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recyclapp.gui;

import java.awt.Color;
import java.io.File;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jeffrey
 */
public class AjouterStation extends javax.swing.JDialog {

    private int sorties;
    private String nom = null;
    private String description;
    private int hauteur;
    private int largeur;
    private Color couleur;
    private int capacite;
    private String cheminImage = null;
   
    public String getNom() {
        return nom;
    }

    public int getSorties() {
        return sorties;
    }

    public String getDescription() {
        return description;
    }

    public int getHauteur() {
        return hauteur;
    }

    public int getLargeur() {
        return largeur;
    }

    public Color getCouleur() {
        return couleur;
    }

    public int getCapacite() {
        return capacite;
    }

    public String getCheminImage() {
        return cheminImage;
    }
    /**
     * Creates new form NewJDialog
     */
    public AjouterStation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        couleur = Color.YELLOW;
        initComponents();
        ApercuCouleur.setBackground(couleur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChoisirImageStation = new javax.swing.JFileChooser();
        ChoisirCouleurStation = new javax.swing.JColorChooser();
        LargeurStation = new javax.swing.JTextField();
        LabelNom = new javax.swing.JLabel();
        Labelx = new javax.swing.JLabel();
        LabelDimensions = new javax.swing.JLabel();
        Labelmetres = new javax.swing.JLabel();
        LabelDescription = new javax.swing.JLabel();
        ConteneurDescriptionStation = new javax.swing.JScrollPane();
        DescriptionStation = new javax.swing.JTextArea();
        HauteurStation = new javax.swing.JTextField();
        NomStation = new javax.swing.JTextField();
        BoutonOK = new javax.swing.JButton();
        BoutonAnnuler = new javax.swing.JButton();
        LabelImage = new javax.swing.JLabel();
        CheminImageStation = new javax.swing.JTextField();
        BoutonParcourirImage = new javax.swing.JButton();
        CapaciteStation = new javax.swing.JTextField();
        BoutonChoisirCouleur = new javax.swing.JButton();
        LabelCapacite = new javax.swing.JLabel();
        LabelCouleur = new javax.swing.JLabel();
        ApercuCouleur = new javax.swing.JLabel();
        NombreSortiesStation = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        ChoisirImageStation.addChoosableFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "tif"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        LargeurStation.setText("3");

        LabelNom.setText("Nom de la station");

        Labelx.setText("x");

        LabelDimensions.setText("Dimensions");

        Labelmetres.setText("mètres");

        LabelDescription.setText("Description");

        DescriptionStation.setColumns(20);
        DescriptionStation.setRows(5);
        ConteneurDescriptionStation.setViewportView(DescriptionStation);

        HauteurStation.setText("3");

        NomStation.setText("Station 1");
        NomStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomStationActionPerformed(evt);
            }
        });

        BoutonOK.setText("OK");
        BoutonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonOKActionPerformed(evt);
            }
        });

        BoutonAnnuler.setText("Annuler");
        BoutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAnnulerActionPerformed(evt);
            }
        });

        LabelImage.setText("Image");

        CheminImageStation.setEditable(false);
        CheminImageStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheminImageStationActionPerformed(evt);
            }
        });

        BoutonParcourirImage.setText("...");
        BoutonParcourirImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonParcourirImageActionPerformed(evt);
            }
        });

        BoutonChoisirCouleur.setText("...");
        BoutonChoisirCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonChoisirCouleurActionPerformed(evt);
            }
        });

        LabelCapacite.setText("Capacité");

        LabelCouleur.setText("Couleur");

        ApercuCouleur.setBackground(new java.awt.Color(255, 255, 255));
        ApercuCouleur.setOpaque(true);

        jLabel1.setText("Sorties");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BoutonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BoutonAnnuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNom)
                            .addComponent(LabelDescription)
                            .addComponent(LabelDimensions)
                            .addComponent(LabelCouleur)
                            .addComponent(LabelImage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheminImageStation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BoutonParcourirImage, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NomStation)
                            .addComponent(ConteneurDescriptionStation, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(BoutonChoisirCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ApercuCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LargeurStation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Labelx)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HauteurStation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Labelmetres)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NombreSortiesStation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelCapacite)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CapaciteStation, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNom)
                    .addComponent(NomStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConteneurDescriptionStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LargeurStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Labelx)
                        .addComponent(LabelDimensions)
                        .addComponent(HauteurStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Labelmetres))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NombreSortiesStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelCouleur)
                        .addComponent(CapaciteStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoutonChoisirCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelCapacite))
                    .addComponent(ApercuCouleur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoutonParcourirImage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CheminImageStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelImage)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonAnnuler)
                    .addComponent(BoutonOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomStationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomStationActionPerformed

    private void CheminImageStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheminImageStationActionPerformed

    }//GEN-LAST:event_CheminImageStationActionPerformed

    private void BoutonChoisirCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonChoisirCouleurActionPerformed
        Color color = ChoisirCouleurStation.showDialog(this, "Choisir une couleur", new Color(0,0,0));
        ApercuCouleur.setBackground(color);
    }//GEN-LAST:event_BoutonChoisirCouleurActionPerformed

    private void BoutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAnnulerActionPerformed
        nom = null;
        this.dispose();
    }//GEN-LAST:event_BoutonAnnulerActionPerformed

    private void BoutonParcourirImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonParcourirImageActionPerformed
        int returnVal = ChoisirImageStation.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = ChoisirImageStation.getSelectedFile();
            CheminImageStation.setText(ChoisirImageStation.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_BoutonParcourirImageActionPerformed

    private void BoutonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonOKActionPerformed
        try {
        if(NomStation.getText().isEmpty()==false && parseInt(NombreSortiesStation.getText()) < 6) {
            nom = NomStation.getText();
            description = DescriptionStation.getText();
            largeur = parseInt(LargeurStation.getText());
            hauteur = parseInt(HauteurStation.getText());
            couleur = ApercuCouleur.getBackground();
            capacite = parseInt(CapaciteStation.getText());
            cheminImage = CheminImageStation.getText();
            sorties = parseInt(NombreSortiesStation.getText());
            this.setVisible(false);
        }
        else if(NomStation.getText().isEmpty()==true){
            BoutonOK.setToolTipText("La station doit posséder un nom");
        }
        else if(parseInt(NombreSortiesStation.getText()) > 5){
            BoutonOK.setToolTipText("La station ne peut avoir plus de 5 sortie");
        }
        }
        catch(NumberFormatException e) {
            BoutonOK.setToolTipText("Les champs 'Sorties', Dimensions' et 'Capacité' doivent être des nombres entiers");
        }
        
    }//GEN-LAST:event_BoutonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterStation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjouterStation dialog = new AjouterStation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApercuCouleur;
    private javax.swing.JButton BoutonAnnuler;
    private javax.swing.JButton BoutonChoisirCouleur;
    private javax.swing.JButton BoutonOK;
    private javax.swing.JButton BoutonParcourirImage;
    private javax.swing.JTextField CapaciteStation;
    private javax.swing.JTextField CheminImageStation;
    private javax.swing.JColorChooser ChoisirCouleurStation;
    private javax.swing.JFileChooser ChoisirImageStation;
    private javax.swing.JScrollPane ConteneurDescriptionStation;
    private javax.swing.JTextArea DescriptionStation;
    private javax.swing.JTextField HauteurStation;
    private javax.swing.JLabel LabelCapacite;
    private javax.swing.JLabel LabelCouleur;
    private javax.swing.JLabel LabelDescription;
    private javax.swing.JLabel LabelDimensions;
    private javax.swing.JLabel LabelImage;
    private javax.swing.JLabel LabelNom;
    private javax.swing.JLabel Labelmetres;
    private javax.swing.JLabel Labelx;
    private javax.swing.JTextField LargeurStation;
    private javax.swing.JTextField NomStation;
    private javax.swing.JTextField NombreSortiesStation;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
