/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recyclapp.gui;

import java.awt.Color;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Jeffrey
 */
public class AjouterJonction extends javax.swing.JDialog {

    String nom = null;
    String description = null;
    Color couleur;
    int capacite;

    public String getNom() {
        return nom;
    }

    public String getDescription() {
        return description;
    }

    public Color getCouleur() {
        return couleur;
    }

    public int getCapacite() {
        return capacite;
    }
    
    /**
     * Creates new form NewJDialog
     */
    public AjouterJonction(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        couleur = Color.LIGHT_GRAY;
        initComponents();
         ApercuCouleur.setBackground(couleur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChoisirCouleurJonction = new javax.swing.JColorChooser();
        BoutonOK = new javax.swing.JButton();
        LabelCouleur = new javax.swing.JLabel();
        ConteneurDescriptionJonction = new javax.swing.JScrollPane();
        DescriptionJonction = new javax.swing.JTextArea();
        NomJonction = new javax.swing.JTextField();
        LabelDescription = new javax.swing.JLabel();
        LabelCapacite = new javax.swing.JLabel();
        BoutonChoisirCouleur = new javax.swing.JButton();
        BoutonAnnuler = new javax.swing.JButton();
        CapaciteJonction = new javax.swing.JTextField();
        LabelNom = new javax.swing.JLabel();
        ApercuCouleur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        BoutonOK.setText("OK");
        BoutonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonOKActionPerformed(evt);
            }
        });

        LabelCouleur.setText("Couleur");

        DescriptionJonction.setColumns(20);
        DescriptionJonction.setRows(5);
        ConteneurDescriptionJonction.setViewportView(DescriptionJonction);

        NomJonction.setText("Jonction 1");
        NomJonction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomJonctionActionPerformed(evt);
            }
        });

        LabelDescription.setText("Description");

        LabelCapacite.setText("Capacité");

        BoutonChoisirCouleur.setText("...");
        BoutonChoisirCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonChoisirCouleurActionPerformed(evt);
            }
        });

        BoutonAnnuler.setText("Annuler");
        BoutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAnnulerActionPerformed(evt);
            }
        });

        LabelNom.setText("Nom de la jonction");

        ApercuCouleur.setBackground(new java.awt.Color(255, 255, 255));
        ApercuCouleur.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BoutonOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BoutonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNom)
                            .addComponent(LabelDescription)
                            .addComponent(LabelCouleur))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoutonChoisirCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ApercuCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(LabelCapacite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CapaciteJonction, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                            .addComponent(NomJonction)
                            .addComponent(ConteneurDescriptionJonction, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNom)
                    .addComponent(NomJonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelDescription)
                    .addComponent(ConteneurDescriptionJonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCapacite)
                            .addComponent(CapaciteJonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ApercuCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BoutonChoisirCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelCouleur)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonAnnuler)
                    .addComponent(BoutonOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomJonctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomJonctionActionPerformed

    }//GEN-LAST:event_NomJonctionActionPerformed

    private void BoutonChoisirCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonChoisirCouleurActionPerformed
        Color color = ChoisirCouleurJonction.showDialog(this, "Choisir une couleur", new Color(0,0,0));
        ApercuCouleur.setBackground(color);
    }//GEN-LAST:event_BoutonChoisirCouleurActionPerformed

    private void BoutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAnnulerActionPerformed
        nom = null;
        this.dispose();
    }//GEN-LAST:event_BoutonAnnulerActionPerformed

    private void BoutonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonOKActionPerformed
        try {
        if(NomJonction.getText().isEmpty()==false) {
            nom = NomJonction.getText();
            description = DescriptionJonction.getText();
            couleur = ApercuCouleur.getBackground();
            capacite = parseInt(CapaciteJonction.getText());
            this.setVisible(false);
        }
        else{
            BoutonOK.setToolTipText("La jonction doit posséder un nom");
        }
        }
        catch(NumberFormatException e) {
            BoutonOK.setToolTipText("Le champ 'Capacité' doit être un nombre entier");
        }
    }//GEN-LAST:event_BoutonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterJonction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterJonction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterJonction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterJonction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjouterJonction dialog = new AjouterJonction(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApercuCouleur;
    private javax.swing.JButton BoutonAnnuler;
    private javax.swing.JButton BoutonChoisirCouleur;
    private javax.swing.JButton BoutonOK;
    private javax.swing.JTextField CapaciteJonction;
    private javax.swing.JColorChooser ChoisirCouleurJonction;
    private javax.swing.JScrollPane ConteneurDescriptionJonction;
    private javax.swing.JTextArea DescriptionJonction;
    private javax.swing.JLabel LabelCapacite;
    private javax.swing.JLabel LabelCouleur;
    private javax.swing.JLabel LabelDescription;
    private javax.swing.JLabel LabelNom;
    private javax.swing.JTextField NomJonction;
    // End of variables declaration//GEN-END:variables
}
