/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recyclapp.gui;

import java.awt.Color;

/**
 *
 * @author Jeffrey
 */
public class AjouterSortie extends javax.swing.JDialog {
    
    String nom = null;
    String description = null;
    Color couleur;

    public String getNom() {
        return nom;
    }

    public String getDescription() {
        return description;
    }

    public Color getCouleur() {
        return couleur;
    }
    /**
     * Creates new form NewJDialog
     */
    public AjouterSortie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        couleur = Color.CYAN;
        initComponents();
        ApercuCouleur.setBackground(couleur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChoisirCouleurSortie = new javax.swing.JColorChooser();
        LabelDescription = new javax.swing.JLabel();
        LabelNom = new javax.swing.JLabel();
        LabelCouleur = new javax.swing.JLabel();
        BoutonOK = new javax.swing.JButton();
        NomSortie = new javax.swing.JTextField();
        BoutonAnnuler = new javax.swing.JButton();
        ConteneurDescriptionSortie = new javax.swing.JScrollPane();
        DescriptionSortie = new javax.swing.JTextArea();
        BoutonChoisirCouleur = new javax.swing.JButton();
        ApercuCouleur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        LabelDescription.setText("Description");

        LabelNom.setText("Nom de la sortie");

        LabelCouleur.setText("Couleur");

        BoutonOK.setText("OK");
        BoutonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonOKActionPerformed(evt);
            }
        });

        NomSortie.setText("Sortie 1");

        BoutonAnnuler.setText("Annuler");
        BoutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAnnulerActionPerformed(evt);
            }
        });

        DescriptionSortie.setColumns(20);
        DescriptionSortie.setRows(5);
        ConteneurDescriptionSortie.setViewportView(DescriptionSortie);

        BoutonChoisirCouleur.setText("...");
        BoutonChoisirCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonChoisirCouleurActionPerformed(evt);
            }
        });

        ApercuCouleur.setBackground(new java.awt.Color(255, 255, 255));
        ApercuCouleur.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(NomSortie, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelCouleur)
                                .addGap(78, 78, 78))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConteneurDescriptionSortie, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoutonChoisirCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ApercuCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BoutonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BoutonAnnuler, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNom)
                    .addComponent(NomSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConteneurDescriptionSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDescription))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ApercuCouleur, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoutonChoisirCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(LabelCouleur)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(199, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BoutonAnnuler)
                        .addComponent(BoutonOK))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonChoisirCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonChoisirCouleurActionPerformed
        Color color = ChoisirCouleurSortie.showDialog(this, "Choisir une couleur", new Color(0,0,0));
        ApercuCouleur.setBackground(color);
    }//GEN-LAST:event_BoutonChoisirCouleurActionPerformed

    private void BoutonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonOKActionPerformed
       if(NomSortie.getText().isEmpty()==false) {
            nom = NomSortie.getText();
            description = DescriptionSortie.getText();
            couleur = ApercuCouleur.getBackground();
            this.setVisible(false);
        }
        else{
            BoutonOK.setToolTipText("La sortie  doit posséder un nom");
        }
    }//GEN-LAST:event_BoutonOKActionPerformed

    private void BoutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAnnulerActionPerformed
        nom = null;
        this.dispose();
    }//GEN-LAST:event_BoutonAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjouterSortie dialog = new AjouterSortie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApercuCouleur;
    private javax.swing.JButton BoutonAnnuler;
    private javax.swing.JButton BoutonChoisirCouleur;
    private javax.swing.JButton BoutonOK;
    private javax.swing.JColorChooser ChoisirCouleurSortie;
    private javax.swing.JScrollPane ConteneurDescriptionSortie;
    private javax.swing.JTextArea DescriptionSortie;
    private javax.swing.JLabel LabelCouleur;
    private javax.swing.JLabel LabelDescription;
    private javax.swing.JLabel LabelNom;
    private javax.swing.JTextField NomSortie;
    // End of variables declaration//GEN-END:variables
}
