/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recyclapp.gui;

import java.awt.Color;
import static java.lang.Integer.parseInt;
import javax.swing.JColorChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import recyclapp.elements.Panier;
import recyclapp.elements.Produit;

/**
 *
 * @author Jeffrey
 */
public class AjouterEntree extends javax.swing.JDialog {

    String nom = null;
    String description = null;
    Color couleur;
    Panier panier;
    public String getNom() {
        return nom;
    }
    
    public Panier getPanier() {
        return panier;
    }
    
    public String getDescription() {
        return description;
    }

    public Color getCouleur() {
        return couleur;
    }

    public JTable getProduitsEntree() {
        return ProduitsEntree;
    }
    
    /**
     * Creates new form NewJDialog
     */
    public AjouterEntree(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        couleur = Color.GREEN;
        initComponents();
        ApercuCouleur.setBackground(couleur);
        
    }
    
    public AjouterEntree(java.awt.Frame parent, boolean modal, String p_nom, String desc, Color c, Panier p) {
        super(parent, modal);
        nom = p_nom;
        description = desc;
        couleur = c;
        panier = p;
        initComponents();
        NomEntree.setText(nom);
        DescriptionEntree.setText(description);
        ApercuCouleur.setBackground(c);
        DefaultTableModel model =  (DefaultTableModel) this.ProduitsEntree.getModel();
        // afficher mon panier dans ma fenetre
        for(int i=0;i<panier.reqPanier().size();i++)
        {
            model.addRow(new Object[]{panier.reqPanier().get(i).reqNomProduit(),Integer.toString(panier.reqPanier().get(i).reqQuantiteProduit())});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChoisirCouleurEntree = new javax.swing.JColorChooser();
        LabelProduitsEntree = new javax.swing.JLabel();
        BoutonAnnuler = new javax.swing.JButton();
        NomEntree = new javax.swing.JTextField();
        LabelCouleur = new javax.swing.JLabel();
        LabelNomEntree = new javax.swing.JLabel();
        ContreneurDescriptionEntree = new javax.swing.JScrollPane();
        DescriptionEntree = new javax.swing.JTextArea();
        LabelDescription = new javax.swing.JLabel();
        BoutonChoisirCouleur = new javax.swing.JButton();
        BoutonOK = new javax.swing.JButton();
        ConteneurProduitsEntree = new javax.swing.JScrollPane();
        ProduitsEntree = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ApercuCouleur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        LabelProduitsEntree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelProduitsEntree.setText("Entrée à créer");

        BoutonAnnuler.setText("Annuler");
        BoutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAnnulerActionPerformed(evt);
            }
        });

        NomEntree.setText("Entrée 1");

        LabelCouleur.setText("Couleur");

        LabelNomEntree.setText("Nom de l'entrée");

        DescriptionEntree.setColumns(20);
        DescriptionEntree.setRows(5);
        ContreneurDescriptionEntree.setViewportView(DescriptionEntree);

        LabelDescription.setText("Description");

        BoutonChoisirCouleur.setText("...");
        BoutonChoisirCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonChoisirCouleurActionPerformed(evt);
            }
        });

        BoutonOK.setText("OK");
        BoutonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonOKActionPerformed(evt);
            }
        });

        ProduitsEntree.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom du produit", "Quantité"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ConteneurProduitsEntree.setViewportView(ProduitsEntree);

        jButton1.setText("Ajouter un produit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Supprimer ce(s) prduit(s)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ApercuCouleur.setBackground(new java.awt.Color(255, 255, 255));
        ApercuCouleur.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BoutonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BoutonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNomEntree)
                            .addComponent(LabelDescription)
                            .addComponent(LabelCouleur))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContreneurDescriptionEntree)
                            .addComponent(NomEntree)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BoutonChoisirCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ApercuCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(ConteneurProduitsEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LabelProduitsEntree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelProduitsEntree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConteneurProduitsEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNomEntree)
                    .addComponent(NomEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContreneurDescriptionEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelCouleur)
                    .addComponent(ApercuCouleur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoutonChoisirCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonAnnuler)
                    .addComponent(BoutonOK))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonChoisirCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonChoisirCouleurActionPerformed
        Color color = ChoisirCouleurEntree.showDialog(this, "Choisir une couleur", new Color(0,0,0));
        ApercuCouleur.setBackground(color);
    }//GEN-LAST:event_BoutonChoisirCouleurActionPerformed

    private void BoutonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonOKActionPerformed
        boolean tableValide = true;
        DefaultTableModel model =  (DefaultTableModel) this.ProduitsEntree.getModel();
        panier = new Panier();
        
        for(int i=0;i<model.getRowCount();i++)
        {
            if (Integer.parseInt(model.getValueAt(i, 1).toString()) <= 0) {tableValide = false;}
            if (model.getValueAt(i, 0).toString().isEmpty() == true) {tableValide = false;}
            Produit monProduit = new Produit();
            monProduit.asgNomProduit(model.getValueAt(i, 0).toString());
            monProduit.asgQuantiteProduit(Integer.parseInt(model.getValueAt(i, 1).toString()));
            panier.ajouterProduit(monProduit);
        }
        if(NomEntree.getText().isEmpty()==false && tableValide == true) {
            nom = NomEntree.getText();
            description = DescriptionEntree.getText();
            couleur = ApercuCouleur.getBackground();
            this.setVisible(false);
        }
        else{
            BoutonOK.setToolTipText("L'entrée  doit posséder un nom, et chaque produit doit posséder un nom et une quantité valide");
        }
    }//GEN-LAST:event_BoutonOKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model =  (DefaultTableModel) this.ProduitsEntree.getModel();
        model.addRow(new Object[]{"Nom du produit", 1});
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model =  (DefaultTableModel) this.ProduitsEntree.getModel();
        int[] rows = ProduitsEntree.getSelectedRows();
        for(int row : rows){
            model.removeRow(ProduitsEntree.convertRowIndexToModel(row));
        }
        ProduitsEntree.clearSelection();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BoutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAnnulerActionPerformed
        nom = null;
        this.dispose();
    }//GEN-LAST:event_BoutonAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterEntree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterEntree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterEntree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterEntree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjouterEntree dialog = new AjouterEntree(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApercuCouleur;
    private javax.swing.JButton BoutonAnnuler;
    private javax.swing.JButton BoutonChoisirCouleur;
    private javax.swing.JButton BoutonOK;
    private javax.swing.JColorChooser ChoisirCouleurEntree;
    private javax.swing.JScrollPane ConteneurProduitsEntree;
    private javax.swing.JScrollPane ContreneurDescriptionEntree;
    private javax.swing.JTextArea DescriptionEntree;
    private javax.swing.JLabel LabelCouleur;
    private javax.swing.JLabel LabelDescription;
    private javax.swing.JLabel LabelNomEntree;
    private javax.swing.JLabel LabelProduitsEntree;
    private javax.swing.JTextField NomEntree;
    private javax.swing.JTable ProduitsEntree;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
