/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recyclapp.gui;

import java.awt.Color;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Jeffrey
 */
public class AjouterConvoyeur extends javax.swing.JDialog {

    Color couleur;
    int capacite;
    boolean confirmation = false;

    public Color getCouleur() {
        return couleur;
    }

    public int getCapacite() {
        return capacite;
    }
    
    /**
     * Creates new form NewJDialog
     */
    public AjouterConvoyeur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        couleur = Color.BLACK;
        initComponents();
        ApercuCouleur.setBackground(couleur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChoisirCouleurConvoyeur = new javax.swing.JColorChooser();
        LabelCouleur = new javax.swing.JLabel();
        CapaciteConvoyeur = new javax.swing.JTextField();
        BoutonOK = new javax.swing.JButton();
        BoutonAnnuler = new javax.swing.JButton();
        LabelCapacite = new javax.swing.JLabel();
        BoutonChoisirCouleur = new javax.swing.JButton();
        ApercuCouleur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        LabelCouleur.setText("Couleur");

        BoutonOK.setText("OK");
        BoutonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonOKActionPerformed(evt);
            }
        });

        BoutonAnnuler.setText("Annuler");
        BoutonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAnnulerActionPerformed(evt);
            }
        });

        LabelCapacite.setText("Capacité");

        BoutonChoisirCouleur.setText("...");
        BoutonChoisirCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonChoisirCouleurActionPerformed(evt);
            }
        });

        ApercuCouleur.setBackground(new java.awt.Color(255, 255, 255));
        ApercuCouleur.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoutonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelCouleur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BoutonChoisirCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ApercuCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(LabelCapacite)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CapaciteConvoyeur)
                    .addComponent(BoutonAnnuler, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ApercuCouleur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelCapacite)
                        .addComponent(CapaciteConvoyeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoutonChoisirCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(LabelCouleur)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonAnnuler)
                    .addComponent(BoutonOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonChoisirCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonChoisirCouleurActionPerformed
        Color color = ChoisirCouleurConvoyeur.showDialog(this, "Choisir une couleur", new Color(0,0,0));
        ApercuCouleur.setBackground(color);
    }//GEN-LAST:event_BoutonChoisirCouleurActionPerformed

    private void BoutonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonOKActionPerformed
        try {
            couleur = ApercuCouleur.getBackground();
            capacite = parseInt(CapaciteConvoyeur.getText());
            confirmation = true;
            this.setVisible(false);
        }
        catch(NumberFormatException e) {
            couleur = ApercuCouleur.getBackground();
            capacite = 1000000;
            confirmation = true;
            this.setVisible(false);
        }
    }//GEN-LAST:event_BoutonOKActionPerformed

    private void BoutonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAnnulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_BoutonAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterConvoyeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterConvoyeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterConvoyeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterConvoyeur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjouterConvoyeur dialog = new AjouterConvoyeur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApercuCouleur;
    private javax.swing.JButton BoutonAnnuler;
    private javax.swing.JButton BoutonChoisirCouleur;
    private javax.swing.JButton BoutonOK;
    private javax.swing.JTextField CapaciteConvoyeur;
    private javax.swing.JColorChooser ChoisirCouleurConvoyeur;
    private javax.swing.JLabel LabelCapacite;
    private javax.swing.JLabel LabelCouleur;
    // End of variables declaration//GEN-END:variables
}
